### ISSUE TITLE
Ad Product 2.0 Public Comment Feedback

### ISSUE THREAD

**Issue by hillslatt** [InteractiveAdvertisingBureau/Taxonomies#9]
Please comment on this issue with feedback on [Ad Product Taxonomy 2.0 ](https://github.com/InteractiveAdvertisingBureau/Taxonomies/blob/develop/Ad%20Product%20Taxonomies/Ad%20Product%20Taxonomy%202.0.tsv)

**Comment by patmmccann** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-462bf9a5-7fff-a528-f582-1046efcd76c0"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Product Taxonomy 2.0 Feedback:</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">We&rsquo;re very excited about the new product taxonomy! Our hope is we can use it to match our publishers&rsquo; ad block preferences and competitive exclusions more accurately than the current default, content taxonomy 1.&nbsp;</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">We were very pleased to find 1:1 matches with these popular blocks</span></p><br /><br /><div dir="ltr" style="margin-left:0pt;" align="left">

IAB8-5 | Cocktails/Beer | 1003New categories:- 1004- 1005 | BeerNew categories:- Hard Sodas, Seltzers, Alco Pops- Spirits
-- | -- | -- | --
IAB8-18 | Wine | 1006 | Wine
IAB7-30 | Infertility | 1372 | Fertility & Family Planning
IAB11-2 | Legal Issues | 1401 | Legal Services
IAB11-4 | Politics | 1459 | Politics
IAB11-5 | Commentary | 1466 | Political Analysis & Opinion
IAB23 | Religion & Spirituality | 1472 | Religion & Spirituality
IAB9-30 | Video & Computer Games | 1114 | Video Games and Consoles
IAB7-44 | Weight Loss | 12811248 | Dieting and WeightlossWeightloss Supplements

</div><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">What&rsquo;s missing?&nbsp;</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">First, it seems Astrology is no longer well defined. Many of our publishers consider astrology advice and astrology products to be quite sensitive. This is IAB15-1 in content 1. It would seem to be an easy fit in PT2 as a subgroup of 1472, religion and spirituality. CT1 defines a variety of specific religious affiliations, eg IAB23-5 and IAB 23-7. We&rsquo;d prefer to restore that detail.</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Dating is IAB14-1 in CT1. We don&rsquo;t see a home in PT2; and we&rsquo;d like subcategories for dating apps, dating websites, as well as short vs long term dating.</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">IAB22-1 is contests and freebies in CT1. We see lottery as 1349 in PT2, but we&rsquo;d prefer something more on the nose, preferably one for contests, one for lotteries, another for freebies. We&rsquo;d also like </span><span style="font-size:10pt;font-family:Arial,sans-serif;color:#1f1f1f;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">multi-level marketing, work from home offers, and online surveys to have a home.</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">In the politics category, 1459, we&rsquo;d love to split out state and local from national contests. We&rsquo;d also prefer to split political issues from political candidates, perhaps by clarifying 1466, referendums and causes. Another issue is ballot measures and referendums appear to be the same thing, so perhaps we could keep ballot measures and delete the word referendum from 1466. IAB7-3 AIDS/HIV and IAB14-3 Gay life no longer have a home.either, and IAB11-1 immigration was important to us to block sometimes as well. We&rsquo;d love to see a few issues broken out under politics such as immigration, civil rights, or others.</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">In PT2 we see 1503 as sexual health. This appears to be missing a variety of sexual products. We&rsquo;d prefer specific designations for toys and other aides, as well as pornography (IAB25-3). We also need swimwear and bathwear (eg robes) as defined groups under clothing (1057). We don&rsquo;t want to see </span><span style="font-size:10pt;font-family:Arial,sans-serif;color:#1f2328;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1269 Bedroom furniture and accessories become muddled with sexual aides, so it is important to give those an explicit home.</span><span style="font-size:10pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /><br /></span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">In CT1 we had IAB26-1, 26-2, 26-3, and 26-4. These all appear to be removed unfortunately. We also need software to be much more flushed out, with toolbars, browser extensions, and downloadable utilities all defined. From AdX, &ldquo;</span><span style="font-size:10pt;font-family:Arial,sans-serif;color:#1f1f1f;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Typical examples include anti-virus software, file converters, driver updaters, system cleaners, download managers, disk defragmenters, codecs, browser toolbars, ringtones, screensavers, wallpapers, and so on.&rdquo;</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">We&rsquo;re hoping to distinguish between online and physical casinos in the gambling group, 1349.&nbsp;</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The new types of loan products are very helpful. Same with drugs, pharma, and tobacco. In the case of Pharma, we&rsquo;d love to see Rx and OTC broken out.&nbsp;</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Cosmetic Services, 1082, includes innocuous things such as hair salons, but also tattoos. We&rsquo;d prefer to make it easier to align with the adx block &lsquo;</span><span style="font-size:10pt;font-family:Arial,sans-serif;color:#000000;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Cosmetic procedures and body modification -</span><span style="font-size:10pt;font-family:Arial,sans-serif;color:#0b57d0;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> </span><span style="font-size:10pt;font-family:Arial,sans-serif;color:#1f1f1f;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Includes lifts, suctions, lasers, hair removal and restoration, tattoos, and body modification.&rsquo;</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#1f1f1f;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">One last comment: we&rsquo;d really prefer links to the appstore are categorized with the category of the linked app, not the app store itself. If it were possible to include comments of that nature in implementation guidelines, we&rsquo;d be delighted.&nbsp;</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#1f1f1f;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Thanks so much!</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Arial,sans-serif;color:#1f1f1f;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Raptive team. </span></p></b><br class="Apple-interchange-newline">
</body>
</html>
